require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FianzensController do

  # This should return the minimal set of attributes required to create a valid
  # Fianzen. As you add validations to Fianzen, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "Datum" => "2013-02-23" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FianzensController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all fianzens as @fianzens" do
      fianzen = Fianzen.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fianzens).should eq([fianzen])
    end
  end

  describe "GET show" do
    it "assigns the requested fianzen as @fianzen" do
      fianzen = Fianzen.create! valid_attributes
      get :show, {:id => fianzen.to_param}, valid_session
      assigns(:fianzen).should eq(fianzen)
    end
  end

  describe "GET new" do
    it "assigns a new fianzen as @fianzen" do
      get :new, {}, valid_session
      assigns(:fianzen).should be_a_new(Fianzen)
    end
  end

  describe "GET edit" do
    it "assigns the requested fianzen as @fianzen" do
      fianzen = Fianzen.create! valid_attributes
      get :edit, {:id => fianzen.to_param}, valid_session
      assigns(:fianzen).should eq(fianzen)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Fianzen" do
        expect {
          post :create, {:fianzen => valid_attributes}, valid_session
        }.to change(Fianzen, :count).by(1)
      end

      it "assigns a newly created fianzen as @fianzen" do
        post :create, {:fianzen => valid_attributes}, valid_session
        assigns(:fianzen).should be_a(Fianzen)
        assigns(:fianzen).should be_persisted
      end

      it "redirects to the created fianzen" do
        post :create, {:fianzen => valid_attributes}, valid_session
        response.should redirect_to(Fianzen.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fianzen as @fianzen" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fianzen.any_instance.stub(:save).and_return(false)
        post :create, {:fianzen => { "Datum" => "invalid value" }}, valid_session
        assigns(:fianzen).should be_a_new(Fianzen)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fianzen.any_instance.stub(:save).and_return(false)
        post :create, {:fianzen => { "Datum" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fianzen" do
        fianzen = Fianzen.create! valid_attributes
        # Assuming there are no other fianzens in the database, this
        # specifies that the Fianzen created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Fianzen.any_instance.should_receive(:update_attributes).with({ "Datum" => "2013-02-23" })
        put :update, {:id => fianzen.to_param, :fianzen => { "Datum" => "2013-02-23" }}, valid_session
      end

      it "assigns the requested fianzen as @fianzen" do
        fianzen = Fianzen.create! valid_attributes
        put :update, {:id => fianzen.to_param, :fianzen => valid_attributes}, valid_session
        assigns(:fianzen).should eq(fianzen)
      end

      it "redirects to the fianzen" do
        fianzen = Fianzen.create! valid_attributes
        put :update, {:id => fianzen.to_param, :fianzen => valid_attributes}, valid_session
        response.should redirect_to(fianzen)
      end
    end

    describe "with invalid params" do
      it "assigns the fianzen as @fianzen" do
        fianzen = Fianzen.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fianzen.any_instance.stub(:save).and_return(false)
        put :update, {:id => fianzen.to_param, :fianzen => { "Datum" => "invalid value" }}, valid_session
        assigns(:fianzen).should eq(fianzen)
      end

      it "re-renders the 'edit' template" do
        fianzen = Fianzen.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fianzen.any_instance.stub(:save).and_return(false)
        put :update, {:id => fianzen.to_param, :fianzen => { "Datum" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fianzen" do
      fianzen = Fianzen.create! valid_attributes
      expect {
        delete :destroy, {:id => fianzen.to_param}, valid_session
      }.to change(Fianzen, :count).by(-1)
    end

    it "redirects to the fianzens list" do
      fianzen = Fianzen.create! valid_attributes
      delete :destroy, {:id => fianzen.to_param}, valid_session
      response.should redirect_to(fianzens_url)
    end
  end

end
