require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FinanzensController do

  # This should return the minimal set of attributes required to create a valid
  # Finanzen. As you add validations to Finanzen, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "datum" => "2013-02-27" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FinanzensController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all finanzens as @finanzens" do
      finanzen = Finanzen.create! valid_attributes
      get :index, {}, valid_session
      assigns(:finanzens).should eq([finanzen])
    end
  end

  describe "GET show" do
    it "assigns the requested finanzen as @finanzen" do
      finanzen = Finanzen.create! valid_attributes
      get :show, {:id => finanzen.to_param}, valid_session
      assigns(:finanzen).should eq(finanzen)
    end
  end

  describe "GET new" do
    it "assigns a new finanzen as @finanzen" do
      get :new, {}, valid_session
      assigns(:finanzen).should be_a_new(Finanzen)
    end
  end

  describe "GET edit" do
    it "assigns the requested finanzen as @finanzen" do
      finanzen = Finanzen.create! valid_attributes
      get :edit, {:id => finanzen.to_param}, valid_session
      assigns(:finanzen).should eq(finanzen)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Finanzen" do
        expect {
          post :create, {:finanzen => valid_attributes}, valid_session
        }.to change(Finanzen, :count).by(1)
      end

      it "assigns a newly created finanzen as @finanzen" do
        post :create, {:finanzen => valid_attributes}, valid_session
        assigns(:finanzen).should be_a(Finanzen)
        assigns(:finanzen).should be_persisted
      end

      it "redirects to the created finanzen" do
        post :create, {:finanzen => valid_attributes}, valid_session
        response.should redirect_to(Finanzen.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved finanzen as @finanzen" do
        # Trigger the behavior that occurs when invalid params are submitted
        Finanzen.any_instance.stub(:save).and_return(false)
        post :create, {:finanzen => { "datum" => "invalid value" }}, valid_session
        assigns(:finanzen).should be_a_new(Finanzen)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Finanzen.any_instance.stub(:save).and_return(false)
        post :create, {:finanzen => { "datum" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested finanzen" do
        finanzen = Finanzen.create! valid_attributes
        # Assuming there are no other finanzens in the database, this
        # specifies that the Finanzen created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Finanzen.any_instance.should_receive(:update_attributes).with({ "datum" => "2013-02-27" })
        put :update, {:id => finanzen.to_param, :finanzen => { "datum" => "2013-02-27" }}, valid_session
      end

      it "assigns the requested finanzen as @finanzen" do
        finanzen = Finanzen.create! valid_attributes
        put :update, {:id => finanzen.to_param, :finanzen => valid_attributes}, valid_session
        assigns(:finanzen).should eq(finanzen)
      end

      it "redirects to the finanzen" do
        finanzen = Finanzen.create! valid_attributes
        put :update, {:id => finanzen.to_param, :finanzen => valid_attributes}, valid_session
        response.should redirect_to(finanzen)
      end
    end

    describe "with invalid params" do
      it "assigns the finanzen as @finanzen" do
        finanzen = Finanzen.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Finanzen.any_instance.stub(:save).and_return(false)
        put :update, {:id => finanzen.to_param, :finanzen => { "datum" => "invalid value" }}, valid_session
        assigns(:finanzen).should eq(finanzen)
      end

      it "re-renders the 'edit' template" do
        finanzen = Finanzen.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Finanzen.any_instance.stub(:save).and_return(false)
        put :update, {:id => finanzen.to_param, :finanzen => { "datum" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested finanzen" do
      finanzen = Finanzen.create! valid_attributes
      expect {
        delete :destroy, {:id => finanzen.to_param}, valid_session
      }.to change(Finanzen, :count).by(-1)
    end

    it "redirects to the finanzens list" do
      finanzen = Finanzen.create! valid_attributes
      delete :destroy, {:id => finanzen.to_param}, valid_session
      response.should redirect_to(finanzens_url)
    end
  end

end
