require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FinanzpositionsController do

  # This should return the minimal set of attributes required to create a valid
  # Finanzposition. As you add validations to Finanzposition, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "FinanzenNr" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FinanzpositionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all finanzpositions as @finanzpositions" do
      finanzposition = Finanzposition.create! valid_attributes
      get :index, {}, valid_session
      assigns(:finanzpositions).should eq([finanzposition])
    end
  end

  describe "GET show" do
    it "assigns the requested finanzposition as @finanzposition" do
      finanzposition = Finanzposition.create! valid_attributes
      get :show, {:id => finanzposition.to_param}, valid_session
      assigns(:finanzposition).should eq(finanzposition)
    end
  end

  describe "GET new" do
    it "assigns a new finanzposition as @finanzposition" do
      get :new, {}, valid_session
      assigns(:finanzposition).should be_a_new(Finanzposition)
    end
  end

  describe "GET edit" do
    it "assigns the requested finanzposition as @finanzposition" do
      finanzposition = Finanzposition.create! valid_attributes
      get :edit, {:id => finanzposition.to_param}, valid_session
      assigns(:finanzposition).should eq(finanzposition)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Finanzposition" do
        expect {
          post :create, {:finanzposition => valid_attributes}, valid_session
        }.to change(Finanzposition, :count).by(1)
      end

      it "assigns a newly created finanzposition as @finanzposition" do
        post :create, {:finanzposition => valid_attributes}, valid_session
        assigns(:finanzposition).should be_a(Finanzposition)
        assigns(:finanzposition).should be_persisted
      end

      it "redirects to the created finanzposition" do
        post :create, {:finanzposition => valid_attributes}, valid_session
        response.should redirect_to(Finanzposition.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved finanzposition as @finanzposition" do
        # Trigger the behavior that occurs when invalid params are submitted
        Finanzposition.any_instance.stub(:save).and_return(false)
        post :create, {:finanzposition => { "FinanzenNr" => "invalid value" }}, valid_session
        assigns(:finanzposition).should be_a_new(Finanzposition)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Finanzposition.any_instance.stub(:save).and_return(false)
        post :create, {:finanzposition => { "FinanzenNr" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested finanzposition" do
        finanzposition = Finanzposition.create! valid_attributes
        # Assuming there are no other finanzpositions in the database, this
        # specifies that the Finanzposition created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Finanzposition.any_instance.should_receive(:update_attributes).with({ "FinanzenNr" => "1" })
        put :update, {:id => finanzposition.to_param, :finanzposition => { "FinanzenNr" => "1" }}, valid_session
      end

      it "assigns the requested finanzposition as @finanzposition" do
        finanzposition = Finanzposition.create! valid_attributes
        put :update, {:id => finanzposition.to_param, :finanzposition => valid_attributes}, valid_session
        assigns(:finanzposition).should eq(finanzposition)
      end

      it "redirects to the finanzposition" do
        finanzposition = Finanzposition.create! valid_attributes
        put :update, {:id => finanzposition.to_param, :finanzposition => valid_attributes}, valid_session
        response.should redirect_to(finanzposition)
      end
    end

    describe "with invalid params" do
      it "assigns the finanzposition as @finanzposition" do
        finanzposition = Finanzposition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Finanzposition.any_instance.stub(:save).and_return(false)
        put :update, {:id => finanzposition.to_param, :finanzposition => { "FinanzenNr" => "invalid value" }}, valid_session
        assigns(:finanzposition).should eq(finanzposition)
      end

      it "re-renders the 'edit' template" do
        finanzposition = Finanzposition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Finanzposition.any_instance.stub(:save).and_return(false)
        put :update, {:id => finanzposition.to_param, :finanzposition => { "FinanzenNr" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested finanzposition" do
      finanzposition = Finanzposition.create! valid_attributes
      expect {
        delete :destroy, {:id => finanzposition.to_param}, valid_session
      }.to change(Finanzposition, :count).by(-1)
    end

    it "redirects to the finanzpositions list" do
      finanzposition = Finanzposition.create! valid_attributes
      delete :destroy, {:id => finanzposition.to_param}, valid_session
      response.should redirect_to(finanzpositions_url)
    end
  end

end
